title: Zectjs-Site
subtitle: ""
description: ""
author: "xx"
language: en
timezone: UTC
url: http:///zectjs.github.io
root: /
permalink: blog/:year/:month/:day/:title/
archive_dir: blog
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: zectjs
deploy:
  type: git
  repo: git@github.com:zectjs/zectjs.github.io.git

disqus_shortname: /zectjs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
swiftype_key: EwN4HMy_KMxTK_GMjV1z
twitter: /zectjs
github: zectjs