menu:
  docs: /docs/
  news: /news/
  plugins: https://github.com/tommy351/hexo/wiki/Plugins
  themes: https://github.com/tommy351/hexo/wiki/Themes

doc_sidebar:
  getting_started:
    overview: index.html
    setup: setup.html
    configuration: configuration.html
    commands: commands.html
    migration: migration.html
  basic_usage:
    writing: writing.html
    drafts: drafts.html
    generating: generating.html
    tag_plugins: tag-plugins.html
    server: server.html
    deployment: deployment.html
  customization:
    permalinks: permalinks.html
    themes: themes.html
    variables: variables.html
    pagination: pagination.html
    helpers: helpers.html
    plugins: plugins.html
  advanced:
    models: models.html
    events: events.html
  miscellaneous:
    troubleshooting: troubleshooting.html
    contributing: contributing.html

google_analytics: UA-4910098-10
fb_admins: 100000247608790
swiftype_key: DDvzs7LQ9kdKssQNQLcv
twitter: hexojs
github: hexojs/hexo